spring:
  application:
    name: StockV1
  datasource:
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:Maxak351#}
    url: jdbc:mysql://${RDS_HOSTNAME:localhost}:${RDS_PORT:3306}/${RDS_DB_NAME:stockmarket}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8083

logging:
  level:
    org.springframework.web: ERROR
    com.market.savecompany: INFO
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: <logPath>/test.log